events {
    worker_connections 1024;
}

http {
    include       /opt/homebrew/etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 8080;
        server_name localhost;

        location / {
            root /Users/danil/Documents/Python/img-host/image-hosting/frontend;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        location /images/ {
            alias /Users/danil/Documents/Python/img-host/image-hosting/images/;
            access_log off;
            expires 30d;
        }

        location /api/ {
            proxy_pass http://127.0.0.1:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            client_max_body_size 5M;
        }

}
}
